---
- name: Install bats-core from source
  git:
    repo: git@github.com:bats-core/bats-core.git
    dest: /tmp/bats-core
    version: master

- name: Install bats-core
  shell: /tmp/bats-core/install.sh /usr/local