---
- name: Install bats-core from source
  ansible.builtin.git:
    repo: git@github.com:bats-core/bats-core.git
    dest: /tmp/bats-core
    version: master

- name: Install bats-core
  changed_when: false
  ansible.builtin.shell: /tmp/bats-core/install.sh /usr/local
