---
- name: Install ZSH
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true

- name: Get ZSH path
  ansible.builtin.shell: which zsh
  register: zsh_path
  changed_when: false

- name: Set user shell to ZSH
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ zsh_path.stdout }}"
  become: true
