---
- name: Install ZSH
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true

- name: Make ZSH the default shell
  changed_when: false
  ansible.builtin.shell: chsh -s $(which zsh)
  become_user: "{{ user }}"
  become: true
