---
- name: Add asciinema repository
  ansible.builtin.apt_repository:
    repo: ppa:zanchey/asciinema
    state: present

- name: Install asciinema
  ansible.builtin.apt:
    name: asciinema
    state: present
  become: true
