---
- name: Download btop
  ansible.builtin.get_url:
    url: https://github.com/aristocratos/btop/releases/download/v{{ btop_version }}/btop-{{ btop_arch }}-{{ btop_os }}-musl.tbz
    dest: /tmp/btop.tbz
    mode: 0755

- name: Create tmp directory
  ansible.builtin.file:
    path: /tmp/btop
    state: directory

- name: Extract btop
  ansible.builtin.unarchive:
    src: /tmp/btop.tbz
    dest: /tmp/btop
    remote_src: true

- name: Install btop
  changed_when: false
  ansible.builtin.shell:
    chdir: /tmp/btop
    command: make install
